spring.datasource.url=jdbc:postgresql://dpg-d7c75tho3t8c73dl69vg-a.oregon-postgres.render.com/univeridadu
spring.datasource.username=admin2
spring.datasource.password=tSHpYCd2mHvlNphyzxrTbk3xGtm0oZYE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
# Para conexiones externas a veces es necesario forzar SSL
spring.datasource.url=jdbc:postgresql://dpg-d7c75tho3t8c73dl69vg-a.oregon-postgres.render.com/univeridadu?sslmode=require
